matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
language: node_js
node_js:
- "6.11.3"
dist: trusty
sudo: true
addons:
compiler:
  - clang
  - gcc
before_install:
  - ./.travis.sh
  - git clone https://github.com/Storj/libstorj.git
  - cd libstorj
  - ./autogen.sh
  - ./configure --prefix=/usr
  - sudo make install  
script:
  - npm install
  - npm run test