matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2
language: node_js
node_js:
- "6.11.3"
dist: trusty
sudo: true
addons:
compiler:
  - clang
  - gcc
before_install:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial main" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial universe" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates universe" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; echo "deb http://us.archive.ubuntu.com/ubuntu/ xenial-updates multiverse" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; echo "deb http://security.ubuntu.com/ubuntu xenial-security main" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; echo "deb http://security.ubuntu.com/ubuntu xenial-security multiverse" | sudo tee -a /etc/apt/sources.list; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; sudo apt-get update -qq; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; sudo apt-get install build-essential libtool autotools-dev automake libmicrohttpd-dev; fi
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; sudo apt-get install libneon27-gnutls-dev nettle-dev libjson-c-dev libuv1-dev; fi
  - git clone https://github.com/Storj/libstorj.git
  - cd libstorj
  - ./autogen.sh
  - ./configure --prefix=/usr
  - sudo make install  
script:
  - npm install
  - npm run test