matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
language: node_js
node_js:
- "6.11.3"
dist: trusty
sudo: true
addons:
compiler:
  - clang
  - gcc
before_install:
  - ./.travis.sh
script:
  - npm install
  - npm run test